---
title: "Data Import Example"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

# Import data
I want to import `FAS_litters.csv`.
```{r}
litters_df <- read.csv("data/FAS_litters.csv")
litters_df <- janitor::clean_names(litters_df)

pups_data = read_csv(file = "./data/FAS_pups.csv")
```

Let's select data
```{r}
select(litters_df, group, litter_number)
select(litters_df, group, gd0_weight, gd_of_birth)
# starts_with, ends_with, contains
select(litters_df, group, starts_with("pups"))

# Rename
select(litters_df, GROUP = group, litter_number)
rename(litters_df, GROUP = group)

# keep everything
select(litters_df, litter_number, everything)
relocate(litters_df, litter_number)
select(pups_df, litter_number, sex, pd_ears)
```

Better names!

```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```

One I use a lot is:
```{r, eval=FALSE}
view(litters_df)
```

Here's `skimr`:
```{r}
skimr::skim(litters_df)
```

## Arguments in `read_csv`

```{r, eval = FALSE}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "Low8")
litters_df
```

## Parsing columns
```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)

## Just correct one column name
## litters_data = read_csv(file = "./data/FAS_litters.csv",
#   col_types = cols(Group = col_character())
```

## Reading from excel

Reading MLB dataset
```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
mlb11_df
```
### Read in a section
```{r}
fellow_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
fellow_df
```
## Read a SAS file
```{r, eval = FALSE}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
pulse_df
```

## why not use `read.csv`
* It import data as data.frame rather than tibble
* Read the data as factor vector
```{r}
litters_df_base = read.csv("data/FAS_litters.csv")
```

## Exporting data
```{r}
write_csv(fellow_df, "data/fellowship_words.csv")
```


