---
title: "Tidy Data"
output: github_document
---
## R Markdown


```{r echo = FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## pivot longer

```{r import}
pulse_df <- read_sas("data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

pulse_df
```

```{r tidy_1}
pulse_tidy <-
  pulse_df %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)
  )
pulse_tidy
```
## pivot_wider

make up a result data table

```{r}
analysis_df <-
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("a","b","a","b"),
    group_mean = c(4, 8, 3, 6)
  )
analysis_df %>%
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>%
  knitr::kable()
```
## Bind rows
```{r}
# Load individual dataset
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

# bind dataframes
lotr_df <-
  bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words"
  ) %>%
  relocate(movie)
# or select(movie, everthing()), select the data.frame by movie names
lotr_df

# Relocate cols
```
* `rbind`, `cbind`? Never use this
Look at FAS data
```{r}
litters_df <- 
  read_csv("data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(dose = str_to_lower(dose))
litters_df

pups_df <-
  read_csv("data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))
pups_df
```

Let's join these up

```{r}
fas_df <-
  left_join(pups_df, litters_df, by="litter_number") 
fas_df
```